# ----- Frontend -----
FROM node:alpine as frontend-build

WORKDIR /app

# copies package.json and package-lock.json
COPY package*.json ./

# install all dependecies inside pack.json 
RUN npm install 

# copy application files to the container 
COPY . . 

# build our react application
RUN npm run build

# stage 2: Serve the application
FROM nginx:alpine

# copy the built React app to Nginx's default HTML directory, where the issue lies 
COPY --from=frontend-build /app/build /usr/share/nginx/html

# expose port, build with port 3000 
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]