# ----- Frontend -----
FROM node:alpine as frontend-build

WORKDIR /app

# copies package.json and package-lock.json
COPY package*.json ./

# Install React 18 and react-router-dom to ensure compatibility
RUN npm install react@18 react-dom@18 react-router-dom

# Install the rest of the dependencies
RUN npm install

# copy application files to the container 
COPY . . 

# build our react application
RUN npm run build

# stage 2: Serve the application
FROM nginx:alpine

# copy the built React app to Nginx's default HTML directory
COPY --from=frontend-build /app/build /usr/share/nginx/html

# expose port, build with port 3000 
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
